### PR TITLE
Sxt7

### PR DESCRIPTION
**Pull request by Pby-25**
use the master branch on backend (as of March 3),
 change getprofile()'s response key from 'name' to 'user'

### CODE REVIEW

**Comment by 1351530910** [comment]
@Pby-25 
2 issues:
first, backend with sp2week1 would be really helpful because this is the branch used by all other front end branches including master.
second, i tried with sp2week1 it prompt me error occured while trying to access profile page. then i tried with master branch backend and it does not display the user name, in my case
image
image

**Comment by Pby-25** [comment]
i'm using the master branch because the getprofile() api is not implemented on sp2week1 branch.

For the username you need to change getprofile()'s response key from 'name' to 'user', or we need to merge the related pull request on backend
https://github.com/Book4U-ECSE428/backend/pull/42

There's other issues with the getprofile() api as well, shall I create an issue on backend?

**Comment by michding** [comment]
@Pby-25 Yeah please create issues on backend

**Comment by wzs1234566** [comment]
included in pr #40

**Pull request closed without merging**
