### PR TITLE
S7T2 with ui for update info

### PR DESCRIPTION
**Pull request by BillChen666**
without js for updating name and gender

### CODE REVIEW

**Comment by billchizhang** [comment]
I think setter is my part, so I should add my code to profile_update.html instead of profile?

**Comment by BillChen666** [comment]
yes please, just call setName, and setgender function there,all other things are set

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billchizhang** [comment]
Is the setter on the front end compatible with the functions on the back end?

**Comment by BillChen666** [comment]
Yep, I used the functions in backend ,and that works fine,just post data in font end to api, it should be good

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billchizhang** [comment]
Ok thanks

**Pull request merged**
